version: '3.8'

services:
  video-dubbing-bot:
    build: .
    container_name: tg-video-bot
    restart: unless-stopped
    volumes:
      - .:/app
    # You can set your environment variables here if you prefer not to hardcode them in config.py
    environment:
      - BOT_TOKEN=your_token_here
      - OWNER_ID=7660990923
      - TELEGRAM_API=28891870
      - TELEGRAM_HASH=ffc3794690bf254d2867ac58fd293a60
