version: '3.8'

services:
  video-dubbing-bot:
    build: .
    container_name: tg-video-bot
    restart: unless-stopped
    volumes:
      - .:/app
    # You can set your environment variables here if you prefer not to hardcode them in config.py
    # Read environment variables from .env file
    env_file:
      - .env
